"""empty message

Revision ID: f0c638563a8f
Revises: 
Create Date: 2020-07-20 18:36:28.955547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0c638563a8f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('army',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ship',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('building', sa.Boolean(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('army_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['army_id'], ['army.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('special',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('details', sa.String(), nullable=True),
    sa.Column('training', sa.Boolean(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('army_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['army_id'], ['army.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('troop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('training', sa.Boolean(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('army_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['army_id'], ['army.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('troop')
    op.drop_table('special')
    op.drop_table('ship')
    op.drop_table('army')
    # ### end Alembic commands ###
